# Generated by Django 5.1.7 on 2025-03-17 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduct',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product', to='store.product'),
        ),
    ]
