# Generated by Django 5.1.7 on 2025-03-19 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_reviewproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitem',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='store.favorite'),
        ),
    ]
